version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/tooling"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
