name: ordinazione
description: "App per gestione ordinazioni Ristorante Candy"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # 🔥 MANTENIAMO LE TUE VERSIONI FIREBASE ESISTENTI
  cloud_firestore: ^4.8.0
  firebase_core: ^2.24.0
  
  # ALTRE TUE DIPENDENZE ESISTENTI
  http: ^1.1.0
  mobile_scanner: ^4.0.0
  provider: ^6.1.1
  reorderables: ^0.6.0
  
  # 🔥 AGGIUNTE PER PERFORMANCE E STABILITÀ
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  qr_flutter: ^4.1.0
  image_picker: ^1.2.0
  # Dependencies for migration CLI (pure Dart, no Flutter)
  googleapis: ^12.0.0
  googleapis_auth: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  fake_cloud_firestore: ^2.5.2

flutter:
  uses-material-design: true
  generate: true  # 🔥 AGGIUNTO PER PERFORMANCE
  
  assets:
    - assets/images/
    - assets/images/pulsanti/
    - assets/images/logo/
    - assets/images/splash.jpg