// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for your platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0gw07rrNLlCOhverPx5vXKZircrNU3MU',
    appId: '1:540813992145:android:7474a38da35a82eb5aa5f0',
    messagingSenderId: '540813992145',
    projectId: 'ordinazione-ristorante-71a70',
    storageBucket: 'ordinazione-ristorante-71a70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlET4BkFw-hxdGpcowZUAP0CFMuTZSS-M',
    appId: '1:540813992145:ios:46729c1e8db76ec25aa5f0',
    messagingSenderId: '540813992145',
    projectId: 'ordinazione-ristorante-71a70',
    storageBucket: 'ordinazione-ristorante-71a70.firebasestorage.app',
    iosBundleId: 'com.candyrestaurant.ordinazione',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0gw07rrNLlCOhverPx5vXKZircrNU3MU',
    appId: '1:540813992145:android:7474a38da35a82eb5aa5f0',
    messagingSenderId: '540813992145',
    projectId: 'ordinazione-ristorante-71a70',
    storageBucket: 'ordinazione-ristorante-71a70.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0gw07rrNLlCOhverPx5vXKZircrNU3MU',
    appId: '1:540813992145:android:7474a38da35a82eb5aa5f0',
    messagingSenderId: '540813992145',
    projectId: 'ordinazione-ristorante-71a70',
    storageBucket: 'ordinazione-ristorante-71a70.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyA0gw07rrNLlCOhverPx5vXKZircrNU3MU',
    appId: '1:540813992145:android:7474a38da35a82eb5aa5f0',
    messagingSenderId: '540813992145',
    projectId: 'ordinazione-ristorante-71a70',
    storageBucket: 'ordinazione-ristorante-71a70.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvB6oK-Qm2VwdQkOitBzx2bepmCddFYkI',
    appId: '1:540813992145:web:9280f641c850cb7c5aa5f0',
    messagingSenderId: '540813992145',
    projectId: 'ordinazione-ristorante-71a70',
    authDomain: 'ordinazione-ristorante-71a70.firebaseapp.com',
    storageBucket: 'ordinazione-ristorante-71a70.firebasestorage.app',
  );
}