// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4LH5x3oOwpwddGG2glk7zchbME5TbA1w',
    appId: '1:1015497862392:web:cb8998c21cbcb44c1c5f0d',
    messagingSenderId: '1015497862392',
    projectId: 'app-ordinazione-ristorante',
    authDomain: 'app-ordinazione-ristorante.firebaseapp.com',
    storageBucket: 'app-ordinazione-ristorante.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzSXFAAYJ4KaHqK6SbeSRJmFDlzXKsyj0',
    appId: '1:1015497862392:android:0237f8fc9bd9bb871c5f0d',
    messagingSenderId: '1015497862392',
    projectId: 'app-ordinazione-ristorante',
    storageBucket: 'app-ordinazione-ristorante.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtSkcxBUj-2uI26we1Yokt2FNScKfGt_I',
    appId: '1:1015497862392:ios:62b8be98d67b018e1c5f0d',
    messagingSenderId: '1015497862392',
    projectId: 'app-ordinazione-ristorante',
    storageBucket: 'app-ordinazione-ristorante.firebasestorage.app',
    iosBundleId: 'com.example.ordinazione',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtSkcxBUj-2uI26we1Yokt2FNScKfGt_I',
    appId: '1:1015497862392:ios:62b8be98d67b018e1c5f0d',
    messagingSenderId: '1015497862392',
    projectId: 'app-ordinazione-ristorante',
    storageBucket: 'app-ordinazione-ristorante.firebasestorage.app',
    iosBundleId: 'com.example.ordinazione',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4LH5x3oOwpwddGG2glk7zchbME5TbA1w',
    appId: '1:1015497862392:web:6e7e44c966138a301c5f0d',
    messagingSenderId: '1015497862392',
    projectId: 'app-ordinazione-ristorante',
    authDomain: 'app-ordinazione-ristorante.firebaseapp.com',
    storageBucket: 'app-ordinazione-ristorante.firebasestorage.app',
  );
}
