name: Emulator tests

on:
  push:
    branches: [ main, master, feature/** ]
  pull_request:
    branches: [ main, master ]

jobs:
  emulator-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency:
      group: emulator-tests
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache npm (tooling)
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            tooling/node_modules
          key: ${{ runner.os }}-npm-tooling-${{ hashFiles('tooling/package-lock.json', 'tooling/package.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-tooling-

      - name: Setup Java (JDK 21)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.6'

      - name: Install firebase-tools
        run: npm install -g firebase-tools

      - name: Cache Flutter/Pub
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ~/.pub-cache/bin
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install tooling deps (npm)
        run: npm ci --prefix tooling

      - name: Get Flutter packages
        run: flutter pub get

      - name: Run emulator-backed tests
        run: |
          # Start emulator(s) and run the helper script inside their context. The helper
          # installs tooling deps, generates the staff token and runs the Dart test.
          chmod +x tooling/ci/run_emulator_tests.sh
          firebase emulators:exec --config firebase.json --only firestore,auth -- ./tooling/ci/run_emulator_tests.sh
