name: Flutter CI

on:
  push:
    branches: [ main, '**' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Flutter tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false

      - name: Ensure .gitmodules is empty
        run: |
          set -e
          # Truncate .gitmodules so git submodule foreach doesn't fail during cleanup
          : > .gitmodules

      - name: Install Flutter (clone stable)
        run: |
          set -e
          echo "Cloning Flutter SDK (stable channel)"
          git clone --depth 1 https://github.com/flutter/flutter.git -b stable $HOME/flutter
          echo "$HOME/flutter/bin" >> $GITHUB_PATH
          echo "$HOME/flutter/bin/cache/dart-sdk/bin" >> $GITHUB_PATH
          export PATH="$HOME/flutter/bin:$HOME/flutter/bin/cache/dart-sdk/bin:$PATH"
          flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Run unit tests
        run: flutter test -r expanded
