name: Static checks

on:
  push:
    branches: [ main, master, feature/**, ci/** ]
  pull_request:
    branches: [ main, master ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.6'

      - name: Get dependencies
        run: flutter pub get

      - name: Dart format check
        run: |
          dart pub global activate dart_style || true
          dart format --output=none --set-exit-if-changed .

      - name: Flutter analyze
        run: flutter analyze
